# Generated by Django 3.2.18 on 2023-04-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_departments_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='image',
            field=models.ImageField(upload_to='Departments'),
        ),
    ]
