# Generated by Django 3.2.18 on 2023-04-02 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_heads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Departmentheads',
        ),
    ]
