# Generated by Django 3.2.18 on 2023-04-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_heads', '0002_rename_departments_departmentheads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentheads',
            name='department',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='departmentheads',
            name='image',
            field=models.ImageField(upload_to='Departmentheads'),
        ),
    ]
