# Generated by Django 3.2.18 on 2023-04-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_heads', '0004_alter_departmentheads_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentheads',
            old_name='name',
            new_name='dhead_name',
        ),
    ]
