# Generated by Django 3.2.18 on 2023-04-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_heads', '0007_alter_departmentheads_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentheads',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
